stages:
    - lint
    - test
    - deploy

variables:
    GIT_DEPTH: 3

.phpcache:
    image:
        name: registry.gitlab.com/hwdegroot/php-json-tool:php-8.1
        entrypoint: [""]
    stage: lint
    variables:
        APP_NAME: php-json-tool
    cache:
        policy: pull
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - vendor/
    before_script:
        - rm -f .php-cs-fixer.cache
        - composer install --no-progress
        - app_key=$(php artisan key:generate --show)
        - export APP_KEY=$app_key

cachefill:php:
    extends: .phpcache
    cache:
        policy: pull-push
    script:
        - "true"

lint:php:syntax:
    extends: .phpcache
    script:
        - vendor/bin/parallel-lint app

lint:php:fix-code-style:
    extends: .phpcache
    script:
        - vendor/bin/php-cs-fixer fix --no-interaction --show-progress=dots -vvv --dry-run

lint:php:copy-paste:
    extends: .phpcache
    script:
        - vendor/bin/phpcpd --fuzzy app

lint:php:mess-detector:
    extends: .phpcache
    script:
        - vendor/bin/phpmd app ansi codesize,controversial,design,naming,unusedcode

coverage:
    stage: test
    extends: .phpcache
    variables:
        PORT: 9000
        XDEBUG_MODE: coverage
    script:
        - rm -rf test-reports
        - mkdir test-reports
        - export APP_URL=http://localhost:${PORT}
        - php artisan serve --port=${PORT} &
        - sleep 1
        - vendor/bin/pest --coverage
    # won't work when output is colored
    coverage: '/Cov.*?([0-9]+\.[0-9]{2})%/'


.deploy:
    stage: deploy
    image: ruby:latest
    before_script:
        - gem install dpl
        - echo CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME >> .env
        - echo CI_COMMIT_SHA=$CI_COMMIT_SHA >> .env
        - echo CI_COMMIT_TAG=$CI_COMMIT_TAG >> .env
        - echo SOURCE_VERSION=$CI_COMMIT_SHA >> .env
    script:
        - dpl --skip_cleanup --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY --strategy=api

deploy_production:
    extends: .deploy
    variables:
        HEROKU_APP: php-json-tool
    only:
        - tags
    when: manual


