version: '3.3'
services:
    web:
        build: .
        command: 'chgrp www-data -R storage bootstrap/cache &&
                  chmod -R ug+rwx storage bootstrap/cache &&
                  cp .env.example .env &&
                  composer install'
        ports:
            - 8080:80
        volumes:
            - .:/var/opt
        working_dir: /var/opt
